function loadHandling(v)	
		if getElementModel(v) == 560 then 									-- bmw 740i
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 211)
			setVehicleHandling(v, "engineAcceleration", 15)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end

		if getElementModel(v) == 579 then 									-- bmw 740i
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0.3, 0.5, 1 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 211)
			setVehicleHandling(v, "engineAcceleration", 25)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end


		if getElementModel(v) == 547 then 									-- bmw m5
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 300)
			setVehicleHandling(v, "engineAcceleration", 22)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end

				if getElementModel(v) == 602 then 									-- mc laren
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 350)
			setVehicleHandling(v, "engineAcceleration", 34)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", true)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.06)
		end


		       if getElementModel(v) == 580 then 									-- lancer evol
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 260)
			setVehicleHandling(v, "engineAcceleration", 16)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end


				       if getElementModel(v) == 550 then 									-- s10
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 10)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end

		     if getElementModel(v) == 492 then 									-- Q7
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 280)
			setVehicleHandling(v, "engineAcceleration", 19)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end


		  if getElementModel(v) == 439 then 									-- BMW Z4
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 280)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.04)
		end


						  if getElementModel(v) == 411 then 									-- Tvip infernus
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 380)
			setVehicleHandling(v, "engineAcceleration", 70)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end

								  if getElementModel(v) == 400 then 									-- Rand Rover
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 12)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end



		  if getElementModel(v) == 402 then 									-- Dodge
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 80)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end


            if getElementModel(v) == 480 then 									-- Porsche
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 400)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end


		            if getElementModel(v) == 585 then 									-- Sonata
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 188)
			setVehicleHandling(v, "engineAcceleration", 13)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end


		            if getElementModel(v) == 415 then 									-- Ferrari sc
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 315)
			setVehicleHandling(v, "engineAcceleration", 29)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end

				            if getElementModel(v) == 445 then 									-- Audi a4 avant
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 185)
			setVehicleHandling(v, "engineAcceleration", 16)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end

						            if getElementModel(v) == 589 then 									-- Audi R8
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 300)
			setVehicleHandling(v, "engineAcceleration", 32)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end

								            if getElementModel(v) == 527 then 									-- Bugatti veyron
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 800)
			setVehicleHandling(v, "engineAcceleration", 54)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end



             if getElementModel(v) == 541 then 									-- Bugatti veyron
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 800)
			setVehicleHandling(v, "engineAcceleration", 59)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end
		if getElementModel(v) == 545 then 									-- Fusca
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 60)
			setVehicleHandling(v, "engineAcceleration", 10)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end
		




end

function loadHandlings()
	for k, v in ipairs(getElementsByType("vehicle")) do
		loadHandling(v)
	end
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), loadHandlings)

function vehicleEnter()
	loadHandling(source)
end
addEventHandler("onVehicleEnter", getRootElement(), vehicleEnter)