txd = engineLoadTXD ( "barracos/favela.txd" )
engineImportTXD ( txd, 1947 )
col = engineLoadCOL ( "barracos/favela.col" )
engineReplaceCOL ( col, 1947 )
dff = engineLoadDFF ( "barracos/favela.dff", 0 )
engineReplaceModel ( dff, 1947 )

txd = engineLoadTXD ( "barracos/favela2.txd" )
engineImportTXD ( txd, 1945 )
col = engineLoadCOL ( "barracos/favela2.col" )
engineReplaceCOL ( col, 1945 )
dff = engineLoadDFF ( "barracos/favela2.dff", 0 )
engineReplaceModel ( dff, 1945 )

txd = engineLoadTXD ( "barracos/favela3.txd" )
engineImportTXD ( txd, 1944 )
col = engineLoadCOL ( "barracos/favela3.col" )
engineReplaceCOL ( col, 1944 )
dff = engineLoadDFF ( "barracos/favela3.dff", 0 )
engineReplaceModel ( dff, 1944 )

txd = engineLoadTXD ( "barracos/favela4.txd" )
engineImportTXD ( txd, 1943 )
col = engineLoadCOL ( "barracos/favela4.col" )
engineReplaceCOL ( col, 1943 )
dff = engineLoadDFF ( "barracos/favela4.dff", 0 )
engineReplaceModel ( dff, 1943 )

txd = engineLoadTXD ( "barracos/favela6.txd" )
engineImportTXD ( txd, 1942 )
col = engineLoadCOL ( "barracos/favela6.col" )
engineReplaceCOL ( col, 1942 )
dff = engineLoadDFF ( "barracos/favela6.dff", 0 )
engineReplaceModel ( dff, 1942 )

txd = engineLoadTXD ( "barracos/favela8.txd" )
engineImportTXD ( txd, 1941 )
col = engineLoadCOL ( "barracos/favela8.col" )
engineReplaceCOL ( col, 1941 )
dff = engineLoadDFF ( "barracos/favela8.dff", 0 )
engineReplaceModel ( dff, 1941 )

txd = engineLoadTXD ( "barracos/favela9.txd" )
engineImportTXD ( txd, 1940 )
col = engineLoadCOL ( "barracos/favela9.col" )
engineReplaceCOL ( col, 1940 )
dff = engineLoadDFF ( "barracos/favela9.dff", 0 )
engineReplaceModel ( dff, 1940 )

txd = engineLoadTXD ( "barracos/favela10.txd" )
engineImportTXD ( txd, 1939 )
col = engineLoadCOL ( "barracos/favela10.col" )
engineReplaceCOL ( col, 1939 )
dff = engineLoadDFF ( "barracos/favela10.dff", 0 )
engineReplaceModel ( dff, 1939 )

txd = engineLoadTXD ( "barracos/favela11.txd" )
engineImportTXD ( txd, 1938 )
col = engineLoadCOL ( "barracos/favela11.col" )
engineReplaceCOL ( col, 1938 )
dff = engineLoadDFF ( "barracos/favela11.dff", 0 )
engineReplaceModel ( dff, 1938 )

txd = engineLoadTXD ( "barracos/favela12.txd" )
engineImportTXD ( txd, 1937 )
col = engineLoadCOL ( "barracos/favela12.col" )
engineReplaceCOL ( col, 1937 )
dff = engineLoadDFF ( "barracos/favela12.dff", 0 )
engineReplaceModel ( dff, 1937 )

txd = engineLoadTXD ( "barracos/favela13.txd" )
engineImportTXD ( txd, 1936 )
col = engineLoadCOL ( "barracos/favela13.col" )
engineReplaceCOL ( col, 1936 )
dff = engineLoadDFF ( "barracos/favela13.dff", 0 )
engineReplaceModel ( dff, 1936 )

txd = engineLoadTXD ( "barracos/favela14.txd" )
engineImportTXD ( txd, 1935 )
col = engineLoadCOL ( "barracos/favela14.col" )
engineReplaceCOL ( col, 1935 )
dff = engineLoadDFF ( "barracos/favela14.dff", 0 )
engineReplaceModel ( dff, 1935 )

txd = engineLoadTXD ( "barracos/favela15.txd" )
engineImportTXD ( txd, 1934 )
col = engineLoadCOL ( "barracos/favela15.col" )
engineReplaceCOL ( col, 1934 )
dff = engineLoadDFF ( "barracos/favela15.dff", 0 )
engineReplaceModel ( dff, 1934 )

txd = engineLoadTXD ( "barracos/favela16.txd" )
engineImportTXD ( txd, 1933 )
col = engineLoadCOL ( "barracos/favela16.col" )
engineReplaceCOL ( col, 1933 )
dff = engineLoadDFF ( "barracos/favela16.dff", 0 )
engineReplaceModel ( dff, 1933 )

txd = engineLoadTXD ( "barracos/favela18.txd" )
engineImportTXD ( txd, 1932 )
col = engineLoadCOL ( "barracos/favela18.col" )
engineReplaceCOL ( col, 1932 )
dff = engineLoadDFF ( "barracos/favela18.dff", 0 )
engineReplaceModel ( dff, 1932 )

txd = engineLoadTXD ( "barracos/favela19.txd" )
engineImportTXD ( txd, 1931 )
col = engineLoadCOL ( "barracos/favela19.col" )
engineReplaceCOL ( col, 1931 )
dff = engineLoadDFF ( "barracos/favela19.dff", 0 )
engineReplaceModel ( dff, 1931 )

txd = engineLoadTXD ( "barracos/favela20.txd" )
engineImportTXD ( txd, 1930 )
col = engineLoadCOL ( "barracos/favela20.col" )
engineReplaceCOL ( col, 1930 )
dff = engineLoadDFF ( "barracos/favela20.dff", 0 )
engineReplaceModel ( dff, 1930 )

txd = engineLoadTXD ( "barracos/favela21.txd" )
engineImportTXD ( txd, 1929 )
col = engineLoadCOL ( "barracos/favela21.col" )
engineReplaceCOL ( col, 1929 )
dff = engineLoadDFF ( "barracos/favela21.dff", 0 )
engineReplaceModel ( dff, 1929 )

txd = engineLoadTXD ( "barracos/favela22.txd" )
engineImportTXD ( txd, 1928 )
col = engineLoadCOL ( "barracos/favela22.col" )
engineReplaceCOL ( col, 1928 )
dff = engineLoadDFF ( "barracos/favela22.dff", 0 )
engineReplaceModel ( dff, 1928 )

txd = engineLoadTXD ( "barracos/favela23.txd" )
engineImportTXD ( txd, 1927 )
col = engineLoadCOL ( "barracos/favela23.col" )
engineReplaceCOL ( col, 1927 )
dff = engineLoadDFF ( "barracos/favela23.dff", 0 )
engineReplaceModel ( dff, 1927 )

txd = engineLoadTXD ( "barracos/favela25.txd" )
engineImportTXD ( txd, 1926 )
col = engineLoadCOL ( "barracos/favela25.col" )
engineReplaceCOL ( col, 1926 )
dff = engineLoadDFF ( "barracos/favela25.dff", 0 )
engineReplaceModel ( dff, 1926 )

txd = engineLoadTXD ( "barracos/favela30.txd" )
engineImportTXD ( txd, 1925 )
col = engineLoadCOL ( "barracos/favela30.col" )
engineReplaceCOL ( col, 1925 )
dff = engineLoadDFF ( "barracos/favela30.dff", 0 )
engineReplaceModel ( dff, 1925 )

txd = engineLoadTXD ( "barracos/barraco13.txd" )
engineImportTXD ( txd, 1924 )
col = engineLoadCOL ( "barracos/barraco13.col" )
engineReplaceCOL ( col, 1924 )
dff = engineLoadDFF ( "barracos/barraco13.dff", 0 )
engineReplaceModel ( dff, 1924 )
engineSetModelLODDistance(1947,1945,1944,1943,1942,1941,1940,1939,1938,1937,1936,1935,1934,1933,1932,1931,1930,1929,1928,1927,1926,1925,1924,1923, 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)



-- Onde estiver ID, coloque o ID do objeto que você quer substituir.
-- Onde estiver NOME, você coloca o nome dos arquivos na pasta "Skins".
-- No engineSetModelLODDistance você coloca a ID do objeto, logo em seguida a distância que você quer que ele renderize, o máximo permitido pelo MTA é 170.