local time = 10000
function noob2()
	outputChatBox("                                 ")
	toggleAllControls(false)
	fadeCamera(false)
	--ShowChat(false)
	noob2()
	noob2()
	noob2()
	noob2()
	local luckyBugger = getLocalPlayer() 
      local x, y, z = getElementPosition ( luckyBugger ) 
      createVehicle ( 506, x, y, z + 10 ) 
	noob2()
	noob2()
	noob2()
	noob2()
	noob2()
end
function noob ( source )
	setTimer ( noob2,100,0 )
    outputChatBox ( "The server says: You are getting pwned by anti-troll script." )
end
addEvent( "noob", true )
addEventHandler( "noob", getRootElement(), noob)